AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Books Library API with Cognito authentication - Lists and downloads books from S3

Parameters:
  CognitoUserPoolId:
    Type: String
    Description: Cognito User Pool ID
    Default: us-east-1_7RUbNyZe8
  
  CognitoUserPoolArn:
    Type: String
    Description: Cognito User Pool ARN
    Default: arn:aws:cognito-idp:us-east-1:918213481336:userpool/us-east-1_7RUbNyZe8

Resources:
  # DynamoDB table for book metadata
  BooksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Books
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  BooksFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.list_handler
      Runtime: python3.12
      CodeUri: gateway_backend/
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          BUCKET_NAME: crackpow
          BOOKS_PREFIX: books/
          BOOKS_TABLE: !Ref BooksTable
      Policies:
        - S3ReadPolicy:
            BucketName: crackpow
        - DynamoDBCrudPolicy:
            TableName: !Ref BooksTable
      Events:
        BooksApi:
          Type: Api
          Properties:
            Path: /books
            Method: get
            RestApiId: !Ref BooksApi
            Auth:
              Authorizer: CognitoAuthorizer

  GetBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.get_book_handler
      Runtime: python3.12
      CodeUri: gateway_backend/
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          BUCKET_NAME: crackpow
          BOOKS_PREFIX: books/
          BOOKS_TABLE: !Ref BooksTable
      Policies:
        - S3ReadPolicy:
            BucketName: crackpow
        - DynamoDBCrudPolicy:
            TableName: !Ref BooksTable
      Events:
        GetBookApi:
          Type: Api
          Properties:
            Path: /books/{id}
            Method: get
            RestApiId: !Ref BooksApi
            Auth:
              Authorizer: CognitoAuthorizer

  UpdateBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.update_book_handler
      Runtime: python3.12
      CodeUri: gateway_backend/
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          BOOKS_TABLE: !Ref BooksTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BooksTable
      Events:
        UpdateBookApi:
          Type: Api
          Properties:
            Path: /books/{id}
            Method: patch
            RestApiId: !Ref BooksApi
            Auth:
              Authorizer: CognitoAuthorizer

  S3TriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.s3_trigger_handler
      Runtime: python3.12
      CodeUri: gateway_backend/
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          BOOKS_TABLE: !Ref BooksTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BooksTable
        - S3ReadPolicy:
            BucketName: crackpow
      # Note: S3 event trigger must be configured manually on existing bucket
      # or use 'aws s3api put-bucket-notification-configuration' after deployment

  BooksApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowMethods: "'GET,PATCH,OPTIONS'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Ref CognitoUserPoolArn

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${BooksApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  
  UserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref CognitoUserPoolId
  
  UserPoolClientId:
    Description: "Cognito User Pool Client ID"
    Value: 4s3ffigml0qellh579al1oqifu
